### ISSUE TITLE
 Not a directory: '/home/data/vip06/miniconda3/envs/DISC/lib/python3.6/site-packages/disc-1.1.2-py3.6.egg/disc'

### ISSUE THREAD

**Issue by TangentDeng** [iyhaoo/DISC#7]
Hi team, thanks for the software. 
I install the DISC in this way:
```
conda create -n DISC python=3.6
pip install disc
```
and later install some requirements by conda or pip
when I run
```
(DISC) vip06@bio3:~$ disc --dataset=day0.loom --out-dir='.'
Traceback (most recent call last):
  File "/home/data/vip06/miniconda3/envs/DISC/bin/disc", line 33, in <module>
    sys.exit(load_entry_point('disc==1.1.2', 'console_scripts', 'disc')())
  File "/home/data/vip06/miniconda3/envs/DISC/lib/python3.6/site-packages/disc-1.1.2-py3.6.egg/disc/__main__.py", line 84, in main
  File "/home/data/vip06/miniconda3/envs/DISC/lib/python3.6/site-packages/disc-1.1.2-py3.6.egg/disc/utils/utility.py", line 29, in running_script_backup
  File "/home/data/vip06/miniconda3/envs/DISC/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
NotADirectoryError: [Errno 20] Not a directory: '/home/data/vip06/miniconda3/envs/DISC/lib/python3.6/site-packages/disc-1.1.2-py3.6.egg/disc'
```
Could you help me? Thanks!

**Comment by iyhaoo** [comment]
Hi,
Thank you very much for using DISC!
Yes, it seems a bug due to conda environment (I cannot recur it because I don't use conda right now). Since this snippet is only for debugging, I just remove it anyway.
Please install DISC again and enjoy it :)
Best,
Hao
